### ISSUE TITLE
Can you make a generic hashing API?

### ISSUE THREAD

**Issue by lin7sh** [starbelly/helium#1]
Hi
The Gimli is very interesting, But I can't find a generic hashing API in Hydro, but it's in libhydrogen.
Can you write more API Nifs to make it useful for hashing

thanks

**Comment by starbelly** [comment]
@mko-io Absolutely. This is on the TODO list for soda as well as requested by @benoitc. Currently am very busy, I will make a soft promise of by next week though. Of course, PRs are welcome too ;) Thank you people for your patience 🙏 
 
 Also,  I'm not sure why but I have not been getting notifications 🤔

**Comment by lin7sh** [comment]
@starbelly  I wish I could help, but currently I don't have the experience with NIF. Your erlang projects is very minimalistic  which I like and the naming is terrific!

**Comment by starbelly** [comment]
No worries @mko-io, I got you covered. Once again appreciate the patience 👍

**Comment by starbelly** [comment]
Have not forgot about this. Should have time over the next few days at this point.

**Comment by starbelly** [comment]
Finally got a chance to start on this. One thing I don't like is that we will have to pass a size to the hash_init functions. In erlang we have to allocate a resource for the state and this requires a size, which really does not does an injustice in regards the elegance of the underlying hydro function... but I can. think of worse things.

**Comment by lin7sh** [comment]
I think for Erlang convention `hash_init/1` is a streamed version of the hash function, if we have to forced to pass a size for now, we can use a blocked version like `make_hash/1` for now.

**Comment by starbelly** [comment]
Yeah, I was thinking on that... and for crypto generic hash in soda as well... Basically, I could not think of a sane default to allocate. If we go with a default size and the caller adds more to the state than is allocated then we will overflow.

**Comment by lin7sh** [comment]
I wish I knew some C to help you working on that.

**Comment by starbelly** [comment]
HAHA no worries. I enjoy this stuff :)

**Comment by starbelly** [comment]
Cheers :)

**Comment by lin7sh** [comment]
good work !

**Comment by starbelly** [comment]
More to come. Gonna put a good bit of work into this over the next few weeks. Need better doc, need more/better tests, need to expose the rest of the API.

**Comment by starbelly** [comment]
@mko-io https://github.com/starbelly/hydro/releases/tag/v0.3.0

**Comment by lin7sh** [comment]
awesome! It will be very useful for micro controller
